### ISSUE TITLE
Rename macos to macOS

### ISSUE THREAD

**Issue by JasonEtco** [matchai/dotfiles#1]
According to [the macOS official website](https://www.apple.com/ca/macos/high-sierra/), the correct casing for Apple's operating system is `macOS`. Therefore, it is a fatal bug that you have named your directory `macos`. Please fix as soon as possible.

**Comment by matchai** [comment]
Thank you for opening an issue.
The casing of all folders in the repo are lowercase for consistency.

Cheers!
